Hw 1
vladseve7n/RS_Team16 pull request #1
Opened 2022-11-20 12:18 UTC by vladseve7n

2022-11-20 14:15 UTC, feldlime commented
Добавляйте, пожалуйста, в ревью, только когда статус чеки будут пройдены, у вас сейчас ошибка 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/14802567/202907116-e5d59e47-4318-45d8-9a8a-84382bc33290.png">

2022-11-20 15:01 UTC, feldlime requested changes

2022-11-20 15:01 UTC, feldlime commented on Dockerfile
> +#CMD ["gunicorn", "main:app", "-c", "gunicorn.config.py"]
Если код не нужен, лучше его сразу удалять, чтобы не оставалось мусора

2022-11-20 15:01 UTC, feldlime commented on docker-compose.local.yml
> +      - ./:/app
Не забывайте ставить пустые строки в конце файлов

2022-11-20 15:01 UTC, feldlime commented on service/api/RecModels.py
> +from abc import ABC, abstractmethod
модули в питоне следует называть в `snake_case` https://peps.python.org/pep-0008/#package-and-module-names

2022-11-20 15:01 UTC, feldlime commented on service/api/RecModels.py
> +    def preparing(self, *args, **kwargs) -> None:
если вы хотите назвать функцию (метод) исходя из того, что она делает, лучше использовать глагол в инфинитиве, а не существительное действия

2022-11-20 15:01 UTC, feldlime commented on service/api/RecModels.py
> +    def preparing(self, *args, **kwargs) -> None:
Использовать `*args, **kwargs` стоит только если это действительно необходимо (например, вы пишите декоратор для произвольной функции)

В данном случае лучше явно прописывать аргументы, которые вам нужны, и их типы

`__init__ ` - в некотором роде исключение, там это можно делать, чтобы была возможность добавлять новые аргументы в наследниках

2022-11-20 15:01 UTC, feldlime commented on service/api/exceptions.py
> +            self,
уехали строки

2022-11-20 15:01 UTC, feldlime commented on service/api/exceptions.py
> +            self,
и тут

2022-11-20 15:01 UTC, feldlime commented on service/api/exceptions.py
> +            self,
дальше тоже, писать больше об этом не буду

2022-11-20 15:01 UTC, feldlime commented on service/api/token.py
> +SECRET_KEY = os.getenv('SECRET_KEY', '000000')
лучше использовать конфиги из `settings.py` - там переменные окружения считываются автоматически

2022-11-20 15:01 UTC, feldlime commented on service/api/views.py
> +class ErrorObject(BaseModel):
подобный класс есть в `models.py`

2022-11-20 15:01 UTC, feldlime commented on service/api/views.py
> +    responses={401: {'model': ErrorResponse}}
на ручку health навешивать авторизацию не нужно

2022-11-20 15:01 UTC, feldlime commented on service/api/views.py
> +    responses={404: {'model': ErrorResponse},
Сейчас не очень понятно, чем отличаются ошибки в случае 401 и 404 ответа. Это лучше конкретизировать

2022-11-20 15:01 UTC, feldlime commented on service/api/views.py
> +        request: Request,
тут снова уехала табуляция

2022-11-20 15:01 UTC, feldlime commented on service/api/views.py
> +    print(authorization)
В продовом коде не стоит использовать `print`

для подобной печати есть логирование и уровень `DEBUG`

2022-11-20 15:01 UTC, feldlime commented on service/api/views.py
> +    model = all_models[model_name]()
Вы 2 раза ищите ключ в словаре: сначала при проверки имени модели, потом здесь. Это не очень удачное решение.

Лучше сделать
```
try:
    model = all_models[model_name]()
except KeyError:
    raise ModelNotFoundError
```

Подробное обсуждение вопроса здесь https://stackoverflow.com/questions/7604636/better-to-try-something-and-catch-the-exception-or-test-if-its-possible-first

2022-11-20 15:01 UTC, feldlime commented on service/api/views.py
> +    reco = model.get_answer(user_id=user_id,
Переносы можно делать по-разному, но стоит придерживаться единого стиля во всем репозитории. Здесь используется другой стиль.

Так что нужно либо переписать везде, либо использовать тот стиль, который есть (в данном случае просто все в одну строку.

Чтобы не думать про подобные вещи, можете воcпользоваться форматтером (black или yapf)

2022-11-20 15:01 UTC, feldlime commented on service/api/token.py
> +SECRET_KEY = os.getenv('SECRET_KEY', '000000')
Не стоит для тех переменных, значение по умолчанию для которых не может быть общеупотребимым, его задавать.

Например, можно указать, что по дефолту число рекомендаций равно 10. Это подойдет во многих случаях. Ключ авторизации, который вы указали как дефолтный, не может быть использован.

2022-11-20 15:01 UTC, feldlime commented on tests/api/test_views.py
> +    assert response.json()["errors"][0]["error_key"] == "model_name_not_found"
Еще нужно добавить тест на неуспешную авторизацию

2022-11-20 15:16 UTC, vladseve7n commented on service/api/RecModels.py
> +from abc import ABC, abstractmethod
Изменил

2022-11-20 15:17 UTC, vladseve7n commented on service/api/RecModels.py
> +    def preparing(self, *args, **kwargs) -> None:
Просто сейчас мы заранее не знаем, какие аргументы нам могут понадобится для модели, поэтому пока решили проблему таким образом

2022-11-21 04:12 UTC, feldlime commented on service/api/RecModels.py
> +    def preparing(self, *args, **kwargs) -> None:
В таком случае лучше написать только то, что нужно сейчас, а потом добавить, чего не хватает.

Чем меньше неопределенности в коде, тем проще его воспринимать. А в проде это очень важно, т.к. чем проще воспринимать код, тем меньше времени тратится на доработки и меньше вероятность ошибиться.

2022-11-22 03:21 UTC, vladseve7n commented on service/api/views.py
> +    print(authorization)
Done

2022-11-23 14:27 UTC, Voronik1801 commented on Dockerfile
> +#CMD ["gunicorn", "main:app", "-c", "gunicorn.config.py"]
Done

2022-11-23 14:27 UTC, Voronik1801 commented on docker-compose.local.yml
> +      - ./:/app
Done

2022-11-23 14:27 UTC, Voronik1801 commented on service/api/RecModels.py
> +    def preparing(self, *args, **kwargs) -> None:
Done

2022-11-23 14:27 UTC, Voronik1801 commented on service/api/exceptions.py
> +            self,
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/exceptions.py
> +            self,
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/token.py
> +SECRET_KEY = os.getenv('SECRET_KEY', '000000')
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/views.py
> +class ErrorObject(BaseModel):
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/views.py
> +    responses={401: {'model': ErrorResponse}}
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/views.py
> +    responses={404: {'model': ErrorResponse},
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/views.py
> +        request: Request,
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/views.py
> +    model = all_models[model_name]()
Done

2022-11-23 14:28 UTC, Voronik1801 commented on service/api/views.py
> +    reco = model.get_answer(user_id=user_id,
Done

2022-11-23 14:28 UTC, Voronik1801 commented on tests/api/test_views.py
> +    assert response.json()["errors"][0]["error_key"] == "model_name_not_found"
Done

2022-11-23 16:17 UTC, feldlime commented on service/api/RecModels.py
> +    def preparing(self, *args, **kwargs) -> None:
я вижу что нет

2022-11-23 16:19 UTC, feldlime commented on service/api/token.py
> +SECRET_KEY = os.getenv('SECRET_KEY', '000000')
но ведь ничего не изменилось

2022-11-23 16:21 UTC, feldlime commented on service/api/views.py
> +        request: Request,
все по-старому

2022-11-24 06:51 UTC, merged