Hw 3
vladseve7n/RS_Team16 pull request #3
Opened 2022-12-10 10:00 UTC by vladseve7n

Order of notebooks:
1) getting_and_preapare_dataset;
2) getting_popular_recos;
3) user_knn_training_models.

2022-12-10 14:49 UTC, feldlime requested changes

2022-12-10 14:49 UTC, feldlime commented on HW_3_notebooks/UserKNN/__init__.py
> +from .user_knn import UserKnn, UserKnnBM25
пустая строка

2022-12-10 14:49 UTC, feldlime commented on HW_3_notebooks/UserKNN/user_knn.py
> +        self.users_inv_mapping = dict(enumerate(train['user_id'].unique()))
дублирование кода, хорошо бы переиспользовать

2022-12-10 14:49 UTC, feldlime commented on HW_3_notebooks/UserKNN/user_knn.py
> +class UserKnnBM25:
че-то я не очень понял где тут bm25

2022-12-10 14:49 UTC, feldlime commented on saved_models/bm25_itemknn_offline.json
> +}
Не забывайте про пустые строки (дальше не пишу)

2022-12-10 14:49 UTC, feldlime commented on service/api/rec_models.py
> +        with open('saved_models/bm25_itemknn_offline.json', 'r') as handle:
не нужно плиз хардкодить пути к файлам, используйте конфиг

2022-12-10 14:49 UTC, feldlime commented on service/api/rec_models.py
> +            self.json_with_recos = json.load(handle)
давайте проясню: json - это **строка** (да, в определенном формате, но строка)

когда делаете `json.load`, получаете словарь

так что не строит называть переменную `json_with_recos`

2022-12-10 14:49 UTC, feldlime commented on service/api/rec_models.py
> +        if str(user_id) not in self.json_with_recos:
1. неэффективно при каждом запросе делать конвертацию в строку. Лучше наоборот при загрузке привести сразу всех в интам.
2. вы сначала чекаете наличие юзера в словаре, а затем достаете его оттуда, то есть делаете поиск дважды. лучше: 
```
try:
    recs = self.json_with_recos[user_id]
except KeyError:
   recs = []
```
А вообще для этого get придумали - `recs = self.json_with_recos.get(user_id, [])`

2022-12-10 14:49 UTC, feldlime commented on service/api/rec_models.py
> +            return [10440, 15297, 4151, 6192, 14,
Давайте-ка это тоже в json засунем, а то стремно

2022-12-10 14:49 UTC, feldlime commented on service/api/views.py
> +        pop_recos = pop_model.get_reco_for_user(user_id=user_id, k_recs=10000)
это ж зачем вам так много-то???

2022-12-10 14:49 UTC, feldlime commented on service/api/views.py
> +        reco.extend(list(set(pop_recos) - set(reco)))
а вы понимаете что таким образом вы порядок теряете? 
<img width="218" alt="image" src="https://user-images.githubusercontent.com/14802567/206861065-21bb3111-2688-4ab9-b738-c23ae48c1e89.png">

2022-12-10 17:59 UTC, feldlime commented
Не очень понимаю, почему ставите `filter_viewed=False`
 По структуре датасета все пары user_id-film_id уникальны, то есть даже если юзер смотрит фильм повторно, новая строка не появляется, то есть если пара юзер-фильм есть в трейне, в тесте она точно не встретится, поэтому рекомендовать фильм, который юзер уже видел, смысла не имеет
<img width="498" alt="image" src="https://user-images.githubusercontent.com/14802567/206868897-20a29367-ec97-4060-9389-de32e921b0c8.png">

2022-12-10 18:07 UTC, feldlime commented
Вы делаете модель item knn, почему называете ее userKNN?
<img width="614" alt="image" src="https://user-images.githubusercontent.com/14802567/206869214-23229ded-2bbd-4e48-993a-f3510e0c42b6.png">

2022-12-11 06:09 UTC, vladseve7n commented on HW_3_notebooks/UserKNN/__init__.py
> +from .user_knn import UserKnn, UserKnnBM25
Done

2022-12-11 06:09 UTC, vladseve7n commented on saved_models/bm25_itemknn_offline.json
> +}
Done

2022-12-11 09:50 UTC, vladseve7n commented on HW_3_notebooks/UserKNN/user_knn.py
> +class UserKnnBM25:
На самом деле это мертворожденный класс, который я хотел использовать для предикта, но никак не могу дать ума, чтобы это закончить, да и времени не хватает, к сожалению

2022-12-11 09:51 UTC, vladseve7n commented on service/api/rec_models.py
> +        with open('saved_models/bm25_itemknn_offline.json', 'r') as handle:
Done

2022-12-11 09:51 UTC, vladseve7n commented on service/api/rec_models.py
> +            self.json_with_recos = json.load(handle)
Done

2022-12-11 09:51 UTC, vladseve7n commented on service/api/rec_models.py
> +        if str(user_id) not in self.json_with_recos:
Done

2022-12-11 09:51 UTC, vladseve7n commented on service/api/rec_models.py
> +            return [10440, 15297, 4151, 6192, 14,
Done

2022-12-11 10:27 UTC, vladseve7n commented on service/api/views.py
> +        pop_recos = pop_model.get_reco_for_user(user_id=user_id, k_recs=10000)
Дело было поздней ночью и мне нужно было просто получить все ответы из заранее заготовленного Dict'a и я ничего лучше не придумал, как это.
Но сейчас поправил!
Done

2022-12-11 10:28 UTC, vladseve7n commented on service/api/views.py
> +        reco.extend(list(set(pop_recos) - set(reco)))
Теперь буду обращать на такое внимание, спасибо!
Done

2022-12-11 17:24 UTC, feldlime commented on HW_3_notebooks/UserKNN/user_knn.py
> +class UserKnnBM25:
в мастер мусор пихать не стоит, пускай себе лежит где-нибудь в отдельной ветке, если думаете, что может пригодиться

2022-12-12 03:49 UTC, vladseve7n commented on HW_3_notebooks/UserKNN/user_knn.py
> +        self.users_inv_mapping = dict(enumerate(train['user_id'].unique()))
Done

2022-12-12 03:49 UTC, vladseve7n commented on HW_3_notebooks/UserKNN/user_knn.py
> +class UserKnnBM25:
Done

2022-12-12 05:00 UTC, feldlime approved these changes

2022-12-13 16:41 UTC, merged